[package]
name = "cerise"
version = "0.1.0"
authors = ["kokone <kokone@kupo.pw>"]
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.64", features = ["GpuTextureFormat"] }

